module.exports = {
    ADD_BOOK: 'ADD_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    RETURN_BOOK: 'RETURN_BOOK',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    LOAD_BOOKLIST: 'LOAD_BOOKLIST',
    LOAD_LIBRARY: 'LOAD_LIBRARY',
    SEARCH_BOOK: 'SEARCH_BOOK',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    LOAD_REPORT: 'LOAD_REPORT',
    UPDATE_BOOK: 'UPDATE_BOOK',
    UPDATE_USER: 'UPDATE_USER',

    START_BORROW_BOOK: 'START_BORROW_BOOK',
    START_RETURN: 'START_RETURN',
    SHOW_ADD: 'SHOW_ADD',
    START_DELETE: 'START_DELETE',
    SHOW_LOGIN: 'SHOW_LOGIN',
    SHOW_CREATE_ACCOUNT: 'SHOW_CREATE_ACCOUNT',


    SIGN_OUT: 'SIGN_OUT',
    SIGN_IN: 'SIGN_IN',
}
